Repository kir-dev/blog-next, pull requests merged in 2021-12, with the labels that each got.

#281 Fix Imagetype inferring
  .gatsby/gatsby-node.ts
  README.md
Labels: bug, high priority

#295 Separate active projects from older ones
  src/pages/projects.tsx
Labels: enhancement, low priority

#294 Added indulaSch description
  src/content/images/projects/indulasch.png
  src/content/projects/indulasch.md
Labels: content
